### PR TITLE
Added support for configurable entities in tilemaps

### PR DESCRIPTION
**Pull request by AbdelHajou**
Using the new addEntity(location, size, entityClass, config) method, different tiles with similar behavior can share the same tile class.

Some examples:

- 'Wall' tiles should all be colliders, but may have different sprites. These can be added using addEntity(location, size, WallTile.class, "sprites/wall_1.png").
- 'Corner' tiles all look the same, but should be rotated based on the corner they're in. Adding four different images for each corner is tedious. Here the config parameter could be the rotation: addEntity(location, size, CornerTile.class, 90).

After this PR has been merged, I will open a pull request to the showcase repo with some uses for this feature. Feedback is appreciated :)

### CODE REVIEW

**Comment by meronbrouwer** [comment]
Just did a quick scan and saw many things that I liked. I'll try to give it a thorough look, but it will take a few days. I'll give my feedback asap.

**Review by meronbrouwer — CHANGES_REQUESTED** [review]
If I see it correctly, the Exception message when the third parameter is of a different type than the provided configuration, doesn't mention anything about the types.
Since all type information is available at that time, we could construct a very specific Exception Message that contains exactly what type is expected.

**Comment by AbdelHajou** [comment]
@meronbrouwer Thanks, added the exception message

**Comment by meronbrouwer** [comment]
@AbdelHajou Great work. There are still some conflicts with master. Can you resolve those? I'll merge your PR afterwards.

**Pull request merged**
