### PR TITLE
Produce mdBook and keep Markdown clean

### LINKED ISSUE #118: Create and deploy an MDBook as part of the workflow
On release we should create and deploy the documentation as a MDBook. 
An interesting feature would be to automatically check the Java code in the MD files to the just-build jar.

### PR DESCRIPTION
**Pull request by sanmai-NL**
Closes #118.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
@meronbrouwer I‘m not sure how we should test whether publishing the book works. First of all, we need a tagged revision, e.g. a release for that part of the job to be triggered. Second, we need to check whether it‘ll interfere with the Javadocs website. Of course, I could enable GitHub Pages on my fork and push a tag. But I‘d rather skip that if you do not mind brief and unlikely breakage of the website. Chances are this‘ll work straight away.

**Comment by sanmai-NL** [comment]
@meronbrouwer The CI failure for the Java CI workflow is spurious. (I advise to skip the Java CI workflow for commits where no Java data was touched at all.)

**Comment by meronbrouwer** [comment]
Thanks for the effort. I'll have a look at this, but that that will probably take a week, because of other priorities.

**Comment by sanmai-NL** [comment]
@meronbrouwer Tested, and made some fixes.

- https://sanmai-nl.github.io/yaeger/
- https://sanmai-nl.github.io/yaeger/book/

After your approval please merge after squash, to reduce the noise of small commits.

**Comment by meronbrouwer** [comment]
Looks promising. I expect to have a thorough look at it next week, before I merge it into master. (Sadly some other things need my attention)

**Pull request merged**
